//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mileage_Logger.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class milageTrackerEntities : DbContext
    {
        public milageTrackerEntities()
            : base("name=milageTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblCar> tblCars { get; set; }
        public virtual DbSet<tblFillUp> tblFillUps { get; set; }
        public virtual DbSet<tblFuelType> tblFuelTypes { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    }
}
