//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mileage_Logger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCar()
        {
            this.tblFillUps = new HashSet<tblFillUp>();
        }
    
        public int Car_ID { get; set; }
        public string Car_Name { get; set; }
        public string Car_Make { get; set; }
        public string Car_Model { get; set; }
        public string Car_NumberPlate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFillUp> tblFillUps { get; set; }
    }
}
