//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Mileage_Logger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFillUp
    {
        public int FillUp_ID { get; set; }
        public int FillUp_Milage { get; set; }
        public int FillUp_Odo { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime FillUp_DateTime { get; set; }
        public int FuelType_ID { get; set; }
        public int Car_ID { get; set; }
        public int User_ID { get; set; }
        public int FillUp_Liters { get; set; }
        public int FillUp_LiterPrice { get; set; }
        public int FillUp_Total { get; set; }
        public string FillUp_SlipImage { get; set; }
    
        public virtual tblCar tblCar { get; set; }
        public virtual tblFuelType tblFuelType { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
